# Generated by Django 6.0.5 on 2026-05-28 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descriptif', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('annee_sortie', models.IntegerField()),
                ('editeur', models.CharField(max_length=100)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.auteur')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('type_joueur', models.CharField(choices=[('pro', 'Professionnel'), ('part', 'Particulier')], max_length=10)),
                ('liste_jeux', models.ManyToManyField(blank=True, to='ludotheque.jeu')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('jeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.jeu')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.joueur')),
            ],
        ),
    ]
