# Generated by Django 6.0.5 on 2026-06-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeu',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
